[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "F12", action = "ToggleFullscreen" },
  { key = "T", mods = "Command", action = "CreateNewTab" },
]

[window]
# window padding {px}
padding.x = 14
padding.y = 14
decorations = "Full"
opacity = 0.98

[font]
normal = { family = "CaskaydiaMono NF", style = "Regular" }
bold = { family = "CaskaydiaMono NF", style = "Bold" }
italic = { family = "CaskaydiaMono NF", style = "Italic" }
size = 12

[colors]
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#7aa2f7'

